name: dark_souls_checklist
description: A new Flutter project.

publish_to: "none"
version: 2.1.1+13

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3
  sqflite: ^2.0.0+2
  url_launcher: ^6.0.2
  flat_buffers: ^2.0.5
  flutter_svg: ^1.1.5
  provider: ^6.0.3
  simple_rich_md:
    path: ../simple_rich_md
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sqlites/
    - assets/i18n/en/flatbuffers/
  fonts:
    - family: OptimusPrinceps
      fonts:
        - asset: assets/fonts/OptimusPrinceps.ttf
          style: normal
        - asset: assets/fonts/OptimusPrincepsSemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Regular.ttf
          style: normal
        - asset: assets/fonts/PlayfairDisplaySC-Italic.ttf
          style: italic
