name: dark_souls_checklist
description: A new Flutter project.

publish_to: "none"
version: 2.1.2+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.12
  flat_buffers: ^2.0.5
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  simple_rich_md:
    path: ../simple_rich_md
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  # Limiting to 6.0.34, since 6.0.35 introduced compatibility issues with
  # AGP 8.0. See https://github.com/flutter/flutter/issues/128204.
  url_launcher_android: 6.0.34

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sqlites/
    - assets/i18n/en/flatbuffers/
    - assets/i18n/fr/flatbuffers/
    - assets/i18n/it/flatbuffers/
    - assets/i18n/pl/flatbuffers/
    - assets/i18n/uk/flatbuffers/
  fonts:
    - family: OptimusPrinceps
      fonts:
        - asset: assets/fonts/OptimusPrinceps.ttf
          style: normal
        - asset: assets/fonts/OptimusPrincepsSemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Regular.ttf
          style: normal
        - asset: assets/fonts/PlayfairDisplaySC-Italic.ttf
          style: italic
