name: simple_rich_md
description: A new Flutter package project.
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0

flutter:
