name: build appbundle in nix develop shell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Pull cache
        run: nix flake prefetch
        
      - name: Build appbundle
        run: nix develop --command buildFlutter appbundle
        
      - name: Upload appbundle
        uses: actions/upload-artifact@v4
        with:
          name: ds3-checklist.appbundle
          path: ds3_checklist/build/app/outputs/flutter-apk/app-release.appbundle
